# https://github.com/nickmerwin/node-coveralls#jest
language: node_js
node_js:
  - "8"
  - node

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage